# Exercício

1. Crie um array NumPy unidimensional com os números de 1 a 10.
   
2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
   
3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
   
4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
11. Dado o array NumPy x = [1, 2, 3], crie:
    
        a) Crie um novo array com os valores de x repetidos três vezes.
        b) Crie um novo array com os valores de x repetidos lado a lado três vezes.
        c) Crie um novo array com os valores de x repetidos verticalmente três vezes.
        d) Inverta a ordem dos elementos do array.
12. Considere o seguinte array bidimensional vendas representando as vendas de produtos em diferentes regiões ao longo de 5 anos, onde cada coluna é um ano e cada linha uam região:
    
            vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])

        a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.
        b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região e exiba os anos correspondentes.
        c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
        d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
        e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.
13. Considere o seguinte array bidimensional notas representando as notas dos alunos em diferentes disciplinas ao longo de 3 trimestres:

            notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])
    
        a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).
        b) Calcule e exiba a média das notas das disciplinas.
        c) Calcule e exiba a média das notas dos alunos.
        d) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

In [1]:
import numpy as np

In [2]:
# 1. Crie um array NumPy unidimensional com os números de 1 a 10.

array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
array = np.zeros((3, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 3. Crie um array NumPy bidimensional 4x4 preenchido com uns.

array = np.ones((4, 4))
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# 4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.

array = np.random.randint(0, 100, 20)
print(array)

[60 36 80 53 92 17  2 39 49 30 91 28 56  4 63 92 23 37 53 12]


In [6]:
np.random.random(20)*100

array([ 5.72317942, 99.23041977, 54.98546931, 89.50544536, 13.48476168,
       55.51406658, 24.02498755, 46.25558359, 27.7485269 , 16.60604712,
       21.71136239, 89.23807875, 75.00496644, 76.79520843, 72.74252828,
        4.09250649,  4.61733556, 35.39029811,  5.87567276, 65.20682051])

In [7]:
np.random.rand(20)*100

array([ 1.26607159, 79.97445883, 66.74847563, 24.72089136, 18.20977988,
       89.50251725,  8.68792128, 81.30898418, 25.25702221,  7.71472263,
       76.36428316, 17.61834345, 48.14258676, 48.93961553, 15.97832063,
       20.99428409, 26.81652014, 92.06045167, 92.62300273, 31.78773366])

In [8]:
# 5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.

array = np.arange(0, 10.5, 0.5)
print(array)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [9]:
# 6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.

array = np.random.randint(1, 101, (5, 5))
print(array)

[[ 2 15 64 20 70]
 [12 55 50 48  4]
 [34 57 38 36 99]
 [98 17 51 54 29]
 [16  7 16 96 79]]


In [10]:
# 7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
segunda_coluna = A[:, 1]
print(segunda_coluna)

[2 5 8]


In [11]:
# 8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.

x = np.array([1, 2, 3, 4, 5])
novo_array = np.where(x % 2 == 0, -1, x)
print(novo_array)

[ 1 -1  3 -1  5]


In [12]:
# 9. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.

x = np.array([1, 2, 3, 4, 5])
novo_array = np.where(x > 2, 0, x)
print(novo_array)

[1 2 0 0 0]


In [13]:
# 10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
multiplicacao = np.dot(A, B)

print(multiplicacao)

[[19 22]
 [43 50]]


In [14]:
# 11 

x = np.array([1, 2, 3])

In [15]:
# a) Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.

novo_array = np.tile(x, 3)
print(novo_array)

[1 2 3 1 2 3 1 2 3]


In [16]:
# b) Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.

novo_array = np.repeat(x, 3)
print(novo_array)

[1 1 1 2 2 2 3 3 3]


In [17]:
# c) Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.

novo_array = np.tile(x, (3, 1))
print(novo_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
# d) Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.

array_invertido = np.flip(x)
print(array_invertido)

[3 2 1]


In [19]:
# 12 

vendas = np.array([
    [100, 150, 200, 120, 180],  # Região 1
    [80, 120, 150, 100, 130],   # Região 2
    [200, 180, 220, 190, 210],  # Região 3
    [150, 160, 170, 140, 180],  # Região 4
    [120, 110, 130, 90, 140]    # Região 5
])

In [20]:
# a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.

media_regioes = np.mean(vendas, axis=1)
print("Média de vendas de cada região ao longo dos 5 anos:", media_regioes)

Média de vendas de cada região ao longo dos 5 anos: [150. 116. 200. 160. 118.]


In [32]:
# b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região.
anos_max_vendas = np.argmax(vendas, axis=1) + 1
print("Ano com o maior número de vendas para cada região:", anos_max_vendas)

# Exibição do ano de vendas de cada loja nos últimos dois anos
for i, ano in enumerate(anos_max_vendas):
    print(f"Na Região {i+1} o maior número de vendas foi do Ano {ano}")

Ano com o maior número de vendas para cada região: [3 3 3 5 5]
Na Região 1 o maior número de vendas foi do Ano 3
Na Região 2 o maior número de vendas foi do Ano 3
Na Região 3 o maior número de vendas foi do Ano 3
Na Região 4 o maior número de vendas foi do Ano 5
Na Região 5 o maior número de vendas foi do Ano 5


In [22]:
# c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
regiao_menor_media = np.argmin(media_regioes) + 1
print("Região com a menor média de vendas ao longo dos 5 anos é a Região", regiao_menor_media)

Região com a menor média de vendas ao longo dos 5 anos é a Região 2


In [23]:
# d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
vendas_lojas = vendas[:, -2:]
vendas_lojas

array([[120, 180],
       [100, 130],
       [190, 210],
       [140, 180],
       [ 90, 140]])

In [24]:
# e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.

media_vendas_lojas = np.mean(vendas_lojas, axis=1)

# Exibição da média de vendas de cada loja nos últimos dois anos
for i, media in enumerate(media_vendas_lojas):
    print(f"Média de vendas da Região {i+1} nos últimos dois anos: {media}")

Média de vendas da Região 1 nos últimos dois anos: 150.0
Média de vendas da Região 2 nos últimos dois anos: 115.0
Média de vendas da Região 3 nos últimos dois anos: 200.0
Média de vendas da Região 4 nos últimos dois anos: 160.0
Média de vendas da Região 5 nos últimos dois anos: 115.0


In [25]:
# 13

notas = np.array([
    [8, 7, 6],
    [9, 8, 7],
    [6, 5, 4],
    [7, 6, 5],
    [10, 9, 8]
])

In [26]:
# a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).

aprovados = notas[(notas >= 7).all(axis=1)]
aprovados

array([[ 9,  8,  7],
       [10,  9,  8]])

In [36]:
# b) Calcule e exiba a média das notas das disciplinas.

media_notas_aprovadas = np.mean(aprovados, axis=0)
media_notas_aprovadas

array([9.5, 8.5, 7.5])

In [37]:
# c) Calcule e exiba a média das notas dos alunos.

media_notas_aprovadas = np.mean(aprovados, axis=1)
media_notas_aprovadas

array([8., 9.])

In [28]:
# d) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

alunos_aprovados_total = len(aprovados)
alunos_aprovados_total

2