# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar com a biblioteca Numpy.


In [1]:
# Importando a biblioteca numpy
import numpy as np

##### Criando arrays numpy

In [2]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo um array.
one_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Imprimindo o array
two_dim.ndim

2

In [7]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.85210625, 0.46435094],
       [0.91488011, 0.83313127],
       [0.11545607, 0.92397437],
       [0.96639845, 0.55781497],
       [0.85096377, 0.47504652]])

In [8]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# cria um array linear de 0 a 2 de 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [13]:
# Criando uma lista em Python.
lista = [1,2,3]

In [14]:
lista

[1, 2, 3]

In [15]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [16]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [17]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [18]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [19]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [20]:
# Faz o calculo usando as listas
pesos / altura ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [22]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [23]:
# Arrays Numpy armazena elementos como strings quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [24]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

In [25]:
a * 2 

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [26]:
# repete o valor do array 2 vezes.
np.tile(a, 2)

array(['1', '3', 'Casa', 'True', '1', '3', 'Casa', 'True'], dtype='<U11')

In [27]:
lista = [1,3,'Casa',True]
lista

[1, 3, 'Casa', True]

In [28]:
lista * 2 

[1, 3, 'Casa', True, 1, 3, 'Casa', True]

In [29]:
lista = [i for i in range(10,50,5)]
lista

[10, 15, 20, 25, 30, 35, 40, 45]

In [30]:
soma = 0
for i in lista:
    soma +=i
    
print('Média:' + str(soma/len(lista)))

Média:27.5


In [31]:
n_array = np.arange(10,50,5)
n_array

array([10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
n_array.mean()

27.5

In [36]:
import time
l1 = list(range(100000))
l2 = np.arange(100000)

start_time = time.time()
%time for i in range(len(l1)): l1[i] = l1[i]*2
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")

start_time = time.time()
%time l = [i*2 for i in l1]
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")

start_time = time.time()
%time l2 = l2 * 2
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")
#%time for i in range(100)

Wall time: 21 ms
Tempo de CPU: 0.021042823791503906 segundos
Wall time: 6.57 ms
Tempo de CPU: 0.007486820220947266 segundos
Wall time: 0 ns
Tempo de CPU: 0.000997781753540039 segundos


In [37]:
lista

[10, 15, 20, 25, 30, 35, 40, 45]

In [38]:
lista[5]

35

In [39]:
lista[lista>20]

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
n_array

array([10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
n_array[5]

35

In [44]:
n_array>20

array([False, False, False,  True,  True,  True,  True,  True])

In [45]:
n_array[n_array>20]

array([25, 30, 35, 40, 45])

# Métodos e Atributos Úteis

In [ ]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

In [46]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [48]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [49]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [50]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [51]:
# Somando todos os elementos do array.
two_dim.sum()

21

In [52]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [53]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [54]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
type(two_dim)

numpy.ndarray

In [55]:
two_dim.dtype

dtype('int32')

In [56]:
two_dim.size

6

#  Transformando Arrays

In [57]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Transforma em uma matriz de uma linha.
# É muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [64]:
# Cria um array com elementos entre 0 e 1 
tree = np.random.random((5,3))
tree

array([[0.42045155, 0.39153651, 0.17385032],
       [0.53569457, 0.25426565, 0.38041914],
       [0.23113657, 0.46254798, 0.89914528],
       [0.41832802, 0.33561743, 0.7405267 ],
       [0.04905918, 0.436578  , 0.67113582]])

In [65]:
tree.shape

(5, 3)

In [66]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.42045155, 0.39153651, 0.17385032, 0.53569457, 0.25426565],
       [0.38041914, 0.23113657, 0.46254798, 0.89914528, 0.41832802],
       [0.33561743, 0.7405267 , 0.04905918, 0.436578  , 0.67113582]])

In [67]:
tree = tree.reshape(-1)
tree

array([0.42045155, 0.39153651, 0.17385032, 0.53569457, 0.25426565,
       0.38041914, 0.23113657, 0.46254798, 0.89914528, 0.41832802,
       0.33561743, 0.7405267 , 0.04905918, 0.436578  , 0.67113582])

In [68]:
tree[0]

0.4204515532306844

In [69]:
t=tree.reshape(1,15)
t

array([[0.42045155, 0.39153651, 0.17385032, 0.53569457, 0.25426565,
        0.38041914, 0.23113657, 0.46254798, 0.89914528, 0.41832802,
        0.33561743, 0.7405267 , 0.04905918, 0.436578  , 0.67113582]])

In [70]:
t[0]

array([0.42045155, 0.39153651, 0.17385032, 0.53569457, 0.25426565,
       0.38041914, 0.23113657, 0.46254798, 0.89914528, 0.41832802,
       0.33561743, 0.7405267 , 0.04905918, 0.436578  , 0.67113582])

## Inserindo e deletando elementos

In [78]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [79]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [73]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [74]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [75]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [80]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

# Nova linha a ser inserida
new_row = np.array([10, 11, 12])

# Inserindo a nova linha no índice 0
two_dim = np.insert(two_dim, 0, new_row, axis=0)
two_dim

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [82]:
# Nova coluna a ser inserida
new_col = np.array([10, 20, 30])

# Inserindo a nova coluna no índice 0
two_dim = np.insert(two_dim, 0, new_col, axis=1)
two_dim

array([[10, 10, 11, 12],
       [20,  1,  2,  3],
       [30,  4,  5,  6]])

In [84]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

## Funções que são úteis e pouco conhecidas

In [85]:
x = np.array([1, 2, 3])
np.repeat(x, 3) # repete o valor dos arrays lado a lado.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [86]:
np.tile(x, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [87]:
np.tile(x, (3, 1)) # repete verticalmente três vezes.

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [88]:
np.flip(x) # inverte a ordem dos elementos do array

array([3, 2, 1])

In [89]:
x = np.array([1, 2, 3, 4, 5])

In [90]:
np.cumprod(x) # produto acumulado de todos os elementos anteriores no array

array([  1,   2,   6,  24, 120])

In [91]:
np.cumsum(x) # soma acumulada de todos os elementos anteriores no array

array([ 1,  3,  6, 10, 15])

In [92]:
x

array([1, 2, 3, 4, 5])

In [93]:
x = np.array([10, 22, 35, 4, 5])

In [94]:
np.diff(x) # diferença de todos os elementos anteriores no array

array([ 12,  13, -31,   1])

In [95]:
np.argsort(x) # ordena os índices dos valores ordenados no arrays

array([3, 4, 0, 1, 2], dtype=int64)

In [96]:
np.sort(x) # ordena os valores ordenados no arrays

array([ 4,  5, 10, 22, 35])

In [97]:
x = np.array([2, 1, 5, 4, 3])
np.argsort(x) 

array([1, 0, 4, 3, 2], dtype=int64)

In [98]:
np.sort(x)

array([1, 2, 3, 4, 5])

# Acessando elementos no Array

In [99]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [100]:
my_array

array([[0.71922503, 0.33122028],
       [0.92641174, 0.32316452],
       [0.05199314, 0.57898284],
       [0.07578834, 0.33350314],
       [0.37415496, 0.86591029],
       [0.99136837, 0.77294611],
       [0.76613645, 0.90337458],
       [0.45857392, 0.30314161],
       [0.98877657, 0.63935718],
       [0.25983858, 0.66837412]])

In [101]:
# Imprimindo os elementos do índice 3
my_array[3]

array([0.07578834, 0.33350314])

In [102]:
my_array[3][1]

0.3335031360193258

In [103]:
# Imprimindo o elemento de índice 1 da coluna 0
my_array[1][0]

0.9264117395444519

In [104]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.3312202843619373

In [105]:
# Segundo elemento da coluna 1
my_array[1][1]

0.3231645176741257

In [106]:
# Segundo elemento da coluna 1, escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.3231645176741257

In [107]:
my_array

array([[0.71922503, 0.33122028],
       [0.92641174, 0.32316452],
       [0.05199314, 0.57898284],
       [0.07578834, 0.33350314],
       [0.37415496, 0.86591029],
       [0.99136837, 0.77294611],
       [0.76613645, 0.90337458],
       [0.45857392, 0.30314161],
       [0.98877657, 0.63935718],
       [0.25983858, 0.66837412]])

In [108]:
# Imprimindo até 3 valores da coluna 1
my_array[0:3,1]

array([0.33122028, 0.32316452, 0.57898284])

In [109]:
# Imprime todas as linhas da coluna 1 * 10
my_array[:,1] * 10

array([3.31220284, 3.23164518, 5.78982839, 3.33503136, 8.65910295,
       7.72946111, 9.03374577, 3.03141614, 6.39357176, 6.68374123])

In [110]:
# Criando um array multidimensional de exemplo
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [111]:
array.ndim

2

In [112]:
# Fatiando o array em linhas
primeiras_linhas = array[:2]
ultima_linha = array[2:]

print("Primeiras linhas:")
print(primeiras_linhas)

print("\nÚltima linha:")
print(ultima_linha)

Primeiras linhas:
[[1 2 3]
 [4 5 6]]

Última linha:
[[7 8 9]]


In [113]:
array[-1]

array([7, 8, 9])

In [114]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
# Fatiando o array em colunas
primeiras_colunas = array[:, :2]
ultima_coluna = array[:, 2:]

print("\nPrimeiras colunas:")
print(primeiras_colunas)

print("\nÚltima coluna:")
print(ultima_coluna)


Primeiras colunas:
[[1 2]
 [4 5]
 [7 8]]

Última coluna:
[[3]
 [6]
 [9]]


In [116]:
n_array = np.arange(1,30,3)
n_array

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [117]:
for i in range(1,len(n_array), 2):
    print(n_array[i])

4
10
16
22
28


In [114]:
# imprimindo os pares
n_array[1::2]

array([ 4, 10, 16, 22, 28])

In [113]:
# imprimindo os ímpares
n_array[::2]

array([ 1,  7, 13, 19, 25])

In [102]:
# imprimir de 1 a 5 pulando 2 numeros
n_array[1:5:2]

array([ 4, 10])

In [122]:
my_array

array([[0.71922503, 0.33122028],
       [0.92641174, 0.32316452],
       [0.05199314, 0.57898284],
       [0.07578834, 0.33350314],
       [0.37415496, 0.86591029],
       [0.99136837, 0.77294611],
       [0.76613645, 0.90337458],
       [0.45857392, 0.30314161],
       [0.98877657, 0.63935718],
       [0.25983858, 0.66837412]])

In [123]:
# Comparação retorna indices
my_array > 0.50

array([[ True, False],
       [ True, False],
       [False,  True],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True],
       [False,  True]])

In [124]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.71922503, 0.92641174, 0.57898284, 0.86591029, 0.99136837,
       0.77294611, 0.76613645, 0.90337458, 0.98877657, 0.63935718,
       0.66837412])

In [125]:
np.sum(my_array[my_array > 0.50])

8.82086326956215

In [126]:
#substituir valores < 0.5
my_array[my_array < 0.50] = 10
my_array

array([[ 0.71922503, 10.        ],
       [ 0.92641174, 10.        ],
       [10.        ,  0.57898284],
       [10.        , 10.        ],
       [10.        ,  0.86591029],
       [ 0.99136837,  0.77294611],
       [ 0.76613645,  0.90337458],
       [10.        , 10.        ],
       [ 0.98877657,  0.63935718],
       [10.        ,  0.66837412]])

In [127]:
my_array = np.random.random([10,2])
print(my_array)
np.where(my_array < 0.50, 10, my_array)

[[0.24180435 0.25641901]
 [0.52626962 0.42303879]
 [0.97034247 0.07961852]
 [0.54431054 0.33145044]
 [0.82997528 0.18438138]
 [0.3094769  0.03957302]
 [0.27834764 0.69088259]
 [0.84524499 0.53631053]
 [0.88950087 0.1109941 ]
 [0.89546764 0.96516613]]


array([[10.        , 10.        ],
       [ 0.52626962, 10.        ],
       [ 0.97034247, 10.        ],
       [ 0.54431054, 10.        ],
       [ 0.82997528, 10.        ],
       [10.        , 10.        ],
       [10.        ,  0.69088259],
       [ 0.84524499,  0.53631053],
       [ 0.88950087, 10.        ],
       [ 0.89546764,  0.96516613]])

In [128]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
# somar as linhas, axis = 1
np.sum(array,axis = 1)

array([ 6, 15, 24])

In [130]:
# somar as colunas, axis = 0
np.sum(array,axis = 0)

array([12, 15, 18])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [131]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('../../Datasets/dataset_array.txt', delimiter=',')

In [132]:
dataset.shape

(6,)

In [133]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [134]:
# carregando um arquivo dividido em 3 arrays
# utilize o unpack para retornar o elemento transposto
a, b, c = np.loadtxt('../../Datasets/dataset_valores.txt', skiprows=1, unpack=True)

In [135]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [136]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [137]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [138]:
# utilize genfromtxt para arquivos com valores faltantes
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!
# utilize filling_values para substituir os valores faltantes ou em strings, pelo valor especificado nesta variável

dataset = np.genfromtxt('../../Datasets/dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [139]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

# Operações Matriciais

In [140]:
a = np.array([100, 200, 300])
print(a)
print(type(a))           
print(a.shape)           
print(a.ndim)            

print(a[0], a[1], a[2])

[100 200 300]
<class 'numpy.ndarray'>
(3,)
1
100 200 300


In [141]:
a[0] = 500                  
print(a)                 

[500 200 300]


In [142]:
b = np.array(
              [
                  [1,2,3],
                  [4,5,6]
              ]
            )  

print(b)
print(b.shape)   
print (b.ndim)   
print(b[0, 0], b[0, 1], b[1, 0])  

[[1 2 3]
 [4 5 6]]
(2, 3)
2
1 2 4


In [143]:
b[0][0] = 2
print(b)

[[2 2 3]
 [4 5 6]]


In [144]:
# Array 3 dimensões

b = np.array( [
                  [
                      [1,2,3],
                      [4,5,6]
                  ],

                  [
                      [1,2,3],
                      [4,5,6]
                  ]
              ]
            )  

print(b)
print(b.shape)  
print (b.ndim)

print (b[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3
6


In [145]:
b[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
b[0][0]

array([1, 2, 3])

In [147]:
b[0][0][0]

1

## Operações

### Soma

In [148]:
#   1 2      5 6      6  8
#         +        =    
#   3 4      7 8      10 12 

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("X:" + str(x) + '\n')
print("Y:" + str(y) + '\n')

# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print()
print(np.add(x, y))


X:[[1. 2.]
 [3. 4.]]

Y:[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [154]:
%%time
print(x + y)

[[ 6.  8.]
 [10. 12.]]
Wall time: 2.11 ms


In [162]:
%%time
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
Wall time: 79.4 µs


### Subtração

In [163]:
#   1 2      5 6      -4  -4
#         -        =    
#   3 4      7 8      -4  -4 

# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print()
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


### Multiplicação

In [164]:
#   1 2      5 6       5  12
#         *        =    
#   3 4      7 8      21  32 

print(x * y)
print()
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [165]:
# Multiplicação matricial
#   1 2      5 6       1*5 + 2*7     1*6 + 2*8
#         x        =    
#   3 4      7 8       3*5 + 4*7     3*6 + 4*8 

print(x.dot(y))
print()
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]

[[19. 22.]
 [43. 50.]]


### Divisão

In [166]:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]

#   1 2      5 6       0.2  0.3333
#         /        =    
#   3 4      7 8       0.428  0.5 

print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Raíz quadrada

In [167]:
%%time
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
Wall time: 1 ms


### Exponencial

In [168]:
x

array([[1., 2.],
       [3., 4.]])

In [169]:
print(np.exp([x]))

[[[ 2.71828183  7.3890561 ]
  [20.08553692 54.59815003]]]


### Logarítmo

In [170]:
print(np.log([x])) # base exponencial
print()
print(np.log10([x]))
print()
print(np.log2([x]))


[[[0.         0.69314718]
  [1.09861229 1.38629436]]]

[[[0.         0.30103   ]
  [0.47712125 0.60205999]]]

[[[0.        1.       ]
  [1.5849625 2.       ]]]


In [171]:
print(np.exp([x]))
print()
print(x)
print()
print(np.log(np.exp([x])))

[[[ 2.71828183  7.3890561 ]
  [20.08553692 54.59815003]]]

[[1. 2.]
 [3. 4.]]

[[[1. 2.]
  [3. 4.]]]


### Matrizes

In [172]:
a = np.zeros((2,2))   # array de zeros
print(a,'\n')              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # array de uns
print(b,'\n')              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # array de constantes
print(c,'\n')               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # matriz identidade
print(d,'\n')              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # array preenchido de valores randomicos entre 0 e 1
print(e,'\n')                    

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[[0.38988547 0.82365181]
 [0.77663056 0.15615096]] 



In [173]:
a = np.array(
              [
                [1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12]
              ]
            )

#print o seguinte array
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print (b,'\n')



[[2 3]
 [6 7]] 



In [174]:
b = a[1:, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [175]:
a[:,0]

array([1, 5, 9])

In [176]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [177]:
print([a[0, 0], a[1, 1], a[2, 0]])

[1, 6, 9]


In [178]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"


print(a[bool_idx])  # Prints "[3 4 5 6]"

print(a[a > 2])     # Prints "[3 4 5 6]"




[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [179]:
array = np.arange(8)
print("Original array : \n", array)
 
# shape array com 2 linhas e 2 colunas
array = np.arange(4).reshape(2, 2)
print("\narray reshaped with 2 rows and 2 columns : \n", array)

# shape array com 4 linhas e 2 colunas
array = np.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n", array)
 
# shape array com 2 linhas e 4 colunas
array = np.arange(8).reshape(2 ,4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# array 3D
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 2 columns : 
 [[0 1]
 [2 3]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [180]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # cria uma matriz vazia do mesmo shape que x

print (y)

# Add o vetor v a cada linha da matrix x com o loop
for i in range(4):
    y[i, :] = x[i, :] + v

# y
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)



[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Conjuntos

##### Usando numpy

In [181]:
A = np.array([1, 2, 3, 4])
B = np.array([3, 4, 5, 6])
print(np.union1d(A, B))
# [1 2 3 4 5 6]
print(np.intersect1d(A, B))
# [3 4]
print(np.setdiff1d(A, B))
# [1 2]
print(np.setdiff1d(B, A))
# [5 6]

[1 2 3 4 5 6]
[3 4]
[1 2]
[5 6]


##### Usando set

In [182]:
A = set(A)
B = set(B)

print(A)
print(B)

{1, 2, 3, 4}
{3, 4, 5, 6}


In [183]:
# União de conjuntos

uniao = A.union(B)
print(uniao)  # Saída: {1, 2, 3, 4, 5, 6}

# Interseção de conjuntos
intersecao = A.intersection(B)
print(intersecao)  # Saída: {3, 4}

# Diferença de conjuntos
diferenca = A.difference(B)
print(diferenca)  # Saída: {1, 2}

# Teste de subconjunto
subconjunto = {1, 2}
print(subconjunto.issubset(A))  # Saída: True


{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
True


### Concatenação

In [184]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.zeros((2, 3))

print(np.concatenate([A, B], axis=0))
# [[1. 2. 3.]
# [4. 5. 6.]
# [0. 0. 0.]
# [0. 0. 0.]]
print()
print(np.concatenate([A, B], axis=1))
# [[1. 2. 3. 0. 0. 0.]
# [4. 5. 6. 0. 0. 0.]]

[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 2. 3. 0. 0. 0.]
 [4. 5. 6. 0. 0. 0.]]


## Máscara booleana e Seleção avançada

In [185]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [186]:
mat[mat > 10]

array([20, 30])

##### Any e All

In [188]:
mat

array([[ 1, 10],
       [20, 30]])

In [189]:
# Podemos fazer operações linha a linha ou coluna a coluna através de métodos auxiliares como any ou all:
# any: se qualquer elemento da linha for True, retorna True
# all: todos os elementos tem que ser True para retornar True
print('Any:')
print(np.any(mat > 10, axis=0)) # Verificando se algum valor em cada coluna é maior que 10
print()
print(np.any(mat > 10, axis=1)) # Verificando se algum valor em cada linha é maior que 10

print()
print('All:')
print(np.all(mat > 10, axis=0)) # Verificando se algum valor em cada coluna é maior que 10
print()
print(np.all(mat > 10, axis=1)) # Verificando se algum valor em cada linha é maior que 10


Any:
[ True  True]

[False  True]

All:
[False False]

[False  True]


##### Operador AND

In [190]:
filt = (mat > 10) & (mat <= 20)
mat[filt]

array([20])

##### Operador OR

In [191]:
filt = (mat == 1) | (mat >= 20)
mat[filt]

array([ 1, 20, 30])

##### Operador NOT

In [192]:
mat[~filt]

array([10])

##### Seleção passando listas

In [193]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

##### np.select()

In [194]:
# Criando uma série de exemplo
s = np.array([0, 5, 10, 15, 20])

# Definindo as condições e as escolhas correspondentes
condicoes = [s < 5, 
             (s >= 5) & (s < 10), 
             (s >= 10) & (s < 15)]

escolhas = ['Grupo A', 'Grupo B', 'Grupo C']

# Aplicando np.select() para criar uma nova série com base nas condições e escolhas
nova_s = np.select(condicoes, escolhas, default='Grupo D')

print(nova_s)


['Grupo A' 'Grupo B' 'Grupo C' 'Grupo D' 'Grupo D']
